version: '3'

services:
  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - "19132:19132/udp"
    volumes:
      - mc-bedrock-data:/data
    restart: always

  bds-flat-creative:
    image: itzg/minecraft-bedrock-server
    container_name: bds-flat-creative
    environment:
      EULA: "TRUE"
      LEVEL_TYPE: flat
      GAMEMODE: creative
    ports:
      - "19133:19132/udp"
    restart: always

volumes:
  mc-bedrock-data:
